/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const JoursSemaine = IDL.Record({
  'mardi' : IDL.Bool,
  'samedi' : IDL.Bool,
  'dimanche' : IDL.Bool,
  'jeudi' : IDL.Bool,
  'lundi' : IDL.Bool,
  'vendredi' : IDL.Bool,
  'mercredi' : IDL.Bool,
});
export const TypeRepetition = IDL.Variant({
  'annuelle' : IDL.Null,
  'aucune' : IDL.Null,
  'hebdomadaire' : JoursSemaine,
  'mensuelle' : IDL.Null,
});
export const ClientReference = IDL.Record({
  'owner' : IDL.Principal,
  'referenceClient' : IDL.Text,
});
export const RendezVousCreateArgs = IDL.Record({
  'montantDu' : IDL.Nat,
  'service' : IDL.Text,
  'dateHeure' : Time,
  'heureFin' : IDL.Text,
  'nomClient' : IDL.Text,
  'repetition' : TypeRepetition,
  'notes' : IDL.Text,
  'adresse' : IDL.Text,
  'clientRef' : ClientReference,
  'heureDebut' : IDL.Text,
  'numeroTelephone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DemandeEdition = IDL.Variant({
  'unique' : IDL.Null,
  'futursDuClient' : IDL.Null,
});
export const ClientRecord = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'clientName' : IDL.Text,
  'owner' : IDL.Principal,
  'referenceClient' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'revenusPercus' : IDL.Nat,
  'totalRecu2026' : IDL.Nat,
  'revenuMoyen2026' : IDL.Nat,
  'revenusPercusMois' : IDL.Nat,
  'totalDue' : IDL.Nat,
  'totalRevenusMensuels2026' : IDL.Vec(IDL.Nat),
  'totalReelRecu' : IDL.Nat,
});
export const RendezVousUpdateArgs = IDL.Record({
  'id' : IDL.Nat,
  'montantDu' : IDL.Nat,
  'service' : IDL.Text,
  'dateHeure' : Time,
  'heureFin' : IDL.Text,
  'nomClient' : IDL.Text,
  'repetition' : TypeRepetition,
  'notes' : IDL.Text,
  'adresse' : IDL.Text,
  'clientRef' : ClientReference,
  'heureDebut' : IDL.Text,
  'numeroTelephone' : IDL.Text,
  'demandeEdition' : DemandeEdition,
});
export const DomaineListingMensuel = IDL.Record({
  'creditMois' : IDL.Int,
  'totalDuesIndividuelles' : IDL.Nat,
  'totalFaitEtPaye' : IDL.Nat,
  'rendezVousFaitsTotal' : IDL.Nat,
  'totalDuMois' : IDL.Nat,
  'nbRendezVousFaits' : IDL.Nat,
  'nomClient' : IDL.Text,
  'soldeCumule' : IDL.Int,
  'totalSommesDues' : IDL.Nat,
  'finExerciceCredit' : IDL.Int,
  'creditFinMois' : IDL.Int,
  'referenceClient' : IDL.Text,
  'soldeRestant' : IDL.Int,
  'totalPayeMois' : IDL.Nat,
  'creditCumule' : IDL.Int,
  'totalReelRecu' : IDL.Int,
});
export const TotauxListingMensuel = IDL.Record({
  'totalTotalReelRecu' : IDL.Int,
  'totalDuesIndividuelles' : IDL.Nat,
  'totalSoldeRestantPositif' : IDL.Int,
  'totalFaitEtPaye' : IDL.Nat,
  'totalDuMois' : IDL.Nat,
  'totalRendezVousFaits' : IDL.Nat,
  'totalSommesDues' : IDL.Nat,
  'totalNbRendezVousFaits' : IDL.Nat,
  'totalPayeMois' : IDL.Nat,
  'totalSoldeRestantNegatif' : IDL.Int,
});
export const RapportType = IDL.Variant({
  'annuel' : IDL.Null,
  'hebdomadaire' : IDL.Null,
  'mensuel' : IDL.Null,
});
export const RapportPDFRequest = IDL.Record({
  'rapportType' : RapportType,
  'period' : IDL.Nat,
  'year' : IDL.Int,
});
export const RapportPDFData = IDL.Record({
  'nbRendezVousFaits' : IDL.Nat,
  'nomClient' : IDL.Text,
  'totalSommesDues' : IDL.Nat,
  'referenceClient' : IDL.Text,
  'totalSommesRecues' : IDL.Nat,
  'totalCredits' : IDL.Nat,
});
export const RendezVous = IDL.Record({
  'id' : IDL.Nat,
  'montantDu' : IDL.Nat,
  'service' : IDL.Text,
  'dateHeure' : Time,
  'owner' : IDL.Principal,
  'fait' : IDL.Bool,
  'heureFin' : IDL.Text,
  'nomClient' : IDL.Text,
  'annule' : IDL.Bool,
  'repetition' : TypeRepetition,
  'paiementAnticipe' : IDL.Bool,
  'montantPaye' : IDL.Nat,
  'referenceClient' : IDL.Text,
  'notes' : IDL.Text,
  'adresse' : IDL.Text,
  'commentaireManuel' : IDL.Text,
  'heureDebut' : IDL.Text,
  'numeroTelephone' : IDL.Text,
});
export const StatistiquesFinancieres = IDL.Record({
  'totalDuesIndividuelles' : IDL.Nat,
  'totalFaitEtPaye' : IDL.Nat,
  'totalDu' : IDL.Nat,
  'totalPaye' : IDL.Nat,
  'totalFaitNonAnnule' : IDL.Nat,
  'totalEnAttente' : IDL.Int,
  'totalReelRecu' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClientRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Vec(IDL.Nat8)),
      ],
      [IDL.Nat],
      [],
    ),
  'ajouterRendezVous' : IDL.Func([RendezVousCreateArgs], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePaidThisYear' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'deleteClientRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteRendezVous' : IDL.Func([IDL.Nat, DemandeEdition], [], []),
  'getAllClientRecords' : IDL.Func([], [IDL.Vec(ClientRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientRecord' : IDL.Func([IDL.Nat], [IDL.Opt(ClientRecord)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getTotalReelRecu' : IDL.Func([IDL.Int, IDL.Int], [IDL.Int], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'handleMontantPayeUpdateWithCredits' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'modifierRendezVous' : IDL.Func([RendezVousUpdateArgs], [], []),
  'obtenirCreditClient' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'obtenirListingMensuel' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(DomaineListingMensuel), TotauxListingMensuel],
      ['query'],
    ),
  'obtenirRapportPDF' : IDL.Func(
      [RapportPDFRequest],
      [IDL.Vec(RapportPDFData)],
      ['query'],
    ),
  'obtenirRendezVous' : IDL.Func([IDL.Nat], [RendezVous], ['query']),
  'obtenirRendezVousParReference' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RendezVous)],
      ['query'],
    ),
  'obtenirRendezVousParStatut' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(RendezVous)],
      ['query'],
    ),
  'obtenirStatistiquesFinancieres' : IDL.Func(
      [],
      [StatistiquesFinancieres],
      ['query'],
    ),
  'obtenirTousLesRendezVous' : IDL.Func([], [IDL.Vec(RendezVous)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClientRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Vec(IDL.Nat8)),
      ],
      [],
      [],
    ),
  'updateCreditClient' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateRendezVousStatus' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Bool), IDL.Opt(IDL.Bool), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const JoursSemaine = IDL.Record({
    'mardi' : IDL.Bool,
    'samedi' : IDL.Bool,
    'dimanche' : IDL.Bool,
    'jeudi' : IDL.Bool,
    'lundi' : IDL.Bool,
    'vendredi' : IDL.Bool,
    'mercredi' : IDL.Bool,
  });
  const TypeRepetition = IDL.Variant({
    'annuelle' : IDL.Null,
    'aucune' : IDL.Null,
    'hebdomadaire' : JoursSemaine,
    'mensuelle' : IDL.Null,
  });
  const ClientReference = IDL.Record({
    'owner' : IDL.Principal,
    'referenceClient' : IDL.Text,
  });
  const RendezVousCreateArgs = IDL.Record({
    'montantDu' : IDL.Nat,
    'service' : IDL.Text,
    'dateHeure' : Time,
    'heureFin' : IDL.Text,
    'nomClient' : IDL.Text,
    'repetition' : TypeRepetition,
    'notes' : IDL.Text,
    'adresse' : IDL.Text,
    'clientRef' : ClientReference,
    'heureDebut' : IDL.Text,
    'numeroTelephone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DemandeEdition = IDL.Variant({
    'unique' : IDL.Null,
    'futursDuClient' : IDL.Null,
  });
  const ClientRecord = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'clientName' : IDL.Text,
    'owner' : IDL.Principal,
    'referenceClient' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'photo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'revenusPercus' : IDL.Nat,
    'totalRecu2026' : IDL.Nat,
    'revenuMoyen2026' : IDL.Nat,
    'revenusPercusMois' : IDL.Nat,
    'totalDue' : IDL.Nat,
    'totalRevenusMensuels2026' : IDL.Vec(IDL.Nat),
    'totalReelRecu' : IDL.Nat,
  });
  const RendezVousUpdateArgs = IDL.Record({
    'id' : IDL.Nat,
    'montantDu' : IDL.Nat,
    'service' : IDL.Text,
    'dateHeure' : Time,
    'heureFin' : IDL.Text,
    'nomClient' : IDL.Text,
    'repetition' : TypeRepetition,
    'notes' : IDL.Text,
    'adresse' : IDL.Text,
    'clientRef' : ClientReference,
    'heureDebut' : IDL.Text,
    'numeroTelephone' : IDL.Text,
    'demandeEdition' : DemandeEdition,
  });
  const DomaineListingMensuel = IDL.Record({
    'creditMois' : IDL.Int,
    'totalDuesIndividuelles' : IDL.Nat,
    'totalFaitEtPaye' : IDL.Nat,
    'rendezVousFaitsTotal' : IDL.Nat,
    'totalDuMois' : IDL.Nat,
    'nbRendezVousFaits' : IDL.Nat,
    'nomClient' : IDL.Text,
    'soldeCumule' : IDL.Int,
    'totalSommesDues' : IDL.Nat,
    'finExerciceCredit' : IDL.Int,
    'creditFinMois' : IDL.Int,
    'referenceClient' : IDL.Text,
    'soldeRestant' : IDL.Int,
    'totalPayeMois' : IDL.Nat,
    'creditCumule' : IDL.Int,
    'totalReelRecu' : IDL.Int,
  });
  const TotauxListingMensuel = IDL.Record({
    'totalTotalReelRecu' : IDL.Int,
    'totalDuesIndividuelles' : IDL.Nat,
    'totalSoldeRestantPositif' : IDL.Int,
    'totalFaitEtPaye' : IDL.Nat,
    'totalDuMois' : IDL.Nat,
    'totalRendezVousFaits' : IDL.Nat,
    'totalSommesDues' : IDL.Nat,
    'totalNbRendezVousFaits' : IDL.Nat,
    'totalPayeMois' : IDL.Nat,
    'totalSoldeRestantNegatif' : IDL.Int,
  });
  const RapportType = IDL.Variant({
    'annuel' : IDL.Null,
    'hebdomadaire' : IDL.Null,
    'mensuel' : IDL.Null,
  });
  const RapportPDFRequest = IDL.Record({
    'rapportType' : RapportType,
    'period' : IDL.Nat,
    'year' : IDL.Int,
  });
  const RapportPDFData = IDL.Record({
    'nbRendezVousFaits' : IDL.Nat,
    'nomClient' : IDL.Text,
    'totalSommesDues' : IDL.Nat,
    'referenceClient' : IDL.Text,
    'totalSommesRecues' : IDL.Nat,
    'totalCredits' : IDL.Nat,
  });
  const RendezVous = IDL.Record({
    'id' : IDL.Nat,
    'montantDu' : IDL.Nat,
    'service' : IDL.Text,
    'dateHeure' : Time,
    'owner' : IDL.Principal,
    'fait' : IDL.Bool,
    'heureFin' : IDL.Text,
    'nomClient' : IDL.Text,
    'annule' : IDL.Bool,
    'repetition' : TypeRepetition,
    'paiementAnticipe' : IDL.Bool,
    'montantPaye' : IDL.Nat,
    'referenceClient' : IDL.Text,
    'notes' : IDL.Text,
    'adresse' : IDL.Text,
    'commentaireManuel' : IDL.Text,
    'heureDebut' : IDL.Text,
    'numeroTelephone' : IDL.Text,
  });
  const StatistiquesFinancieres = IDL.Record({
    'totalDuesIndividuelles' : IDL.Nat,
    'totalFaitEtPaye' : IDL.Nat,
    'totalDu' : IDL.Nat,
    'totalPaye' : IDL.Nat,
    'totalFaitNonAnnule' : IDL.Nat,
    'totalEnAttente' : IDL.Int,
    'totalReelRecu' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClientRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Vec(IDL.Nat8)),
        ],
        [IDL.Nat],
        [],
      ),
    'ajouterRendezVous' : IDL.Func([RendezVousCreateArgs], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePaidThisYear' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'deleteClientRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteRendezVous' : IDL.Func([IDL.Nat, DemandeEdition], [], []),
    'getAllClientRecords' : IDL.Func([], [IDL.Vec(ClientRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientRecord' : IDL.Func([IDL.Nat], [IDL.Opt(ClientRecord)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getTotalReelRecu' : IDL.Func([IDL.Int, IDL.Int], [IDL.Int], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'handleMontantPayeUpdateWithCredits' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'modifierRendezVous' : IDL.Func([RendezVousUpdateArgs], [], []),
    'obtenirCreditClient' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'obtenirListingMensuel' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(DomaineListingMensuel), TotauxListingMensuel],
        ['query'],
      ),
    'obtenirRapportPDF' : IDL.Func(
        [RapportPDFRequest],
        [IDL.Vec(RapportPDFData)],
        ['query'],
      ),
    'obtenirRendezVous' : IDL.Func([IDL.Nat], [RendezVous], ['query']),
    'obtenirRendezVousParReference' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RendezVous)],
        ['query'],
      ),
    'obtenirRendezVousParStatut' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(RendezVous)],
        ['query'],
      ),
    'obtenirStatistiquesFinancieres' : IDL.Func(
        [],
        [StatistiquesFinancieres],
        ['query'],
      ),
    'obtenirTousLesRendezVous' : IDL.Func([], [IDL.Vec(RendezVous)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClientRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Vec(IDL.Nat8)),
        ],
        [],
        [],
      ),
    'updateCreditClient' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateRendezVousStatus' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Bool), IDL.Opt(IDL.Bool), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };