/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientRecord {
  'id' : bigint,
  'service' : string,
  'clientName' : string,
  'owner' : Principal,
  'referenceClient' : string,
  'address' : string,
  'notes' : string,
  'photo' : [] | [Uint8Array],
  'phoneNumber' : string,
}
export interface DashboardStats {
  'revenusPercus' : bigint,
  'totalRecu2026' : bigint,
  'revenuMoyen2026' : bigint,
  'revenusPercusMois' : bigint,
  'totalDue' : bigint,
  'totalRevenusMensuels2026' : Array<bigint>,
  'totalReelRecu' : bigint,
}
export type DemandeEdition = { 'unique' : null } |
  { 'futursDuClient' : null };
export interface DomaineListingMensuel {
  'creditMois' : bigint,
  'totalDuesIndividuelles' : bigint,
  'totalFaitEtPaye' : bigint,
  'rendezVousFaitsTotal' : bigint,
  'totalDuMois' : bigint,
  'nbRendezVousFaits' : bigint,
  'nomClient' : string,
  'soldeCumule' : bigint,
  'totalSommesDues' : bigint,
  'finExerciceCredit' : bigint,
  'creditFinMois' : bigint,
  'referenceClient' : string,
  'soldeRestant' : bigint,
  'totalPayeMois' : bigint,
  'creditCumule' : bigint,
  'totalReelRecu' : bigint,
}
export interface JoursSemaine {
  'mardi' : boolean,
  'samedi' : boolean,
  'dimanche' : boolean,
  'jeudi' : boolean,
  'lundi' : boolean,
  'vendredi' : boolean,
  'mercredi' : boolean,
}
export interface RapportPDFData {
  'nbRendezVousFaits' : bigint,
  'nomClient' : string,
  'totalSommesDues' : bigint,
  'referenceClient' : string,
  'totalSommesRecues' : bigint,
  'totalCredits' : bigint,
}
export interface RapportPDFRequest {
  'rapportType' : RapportType,
  'period' : bigint,
  'year' : bigint,
}
export type RapportType = { 'annuel' : null } |
  { 'hebdomadaire' : null } |
  { 'mensuel' : null };
export interface RendezVous {
  'id' : bigint,
  'montantDu' : bigint,
  'service' : string,
  'dateHeure' : Time,
  'owner' : Principal,
  'fait' : boolean,
  'heureFin' : string,
  'nomClient' : string,
  'annule' : boolean,
  'repetition' : TypeRepetition,
  'paiementAnticipe' : boolean,
  'montantPaye' : bigint,
  'referenceClient' : string,
  'notes' : string,
  'adresse' : string,
  'commentaireManuel' : string,
  'heureDebut' : string,
  'numeroTelephone' : string,
}
export interface StatistiquesFinancieres {
  'totalDuesIndividuelles' : bigint,
  'totalFaitEtPaye' : bigint,
  'totalDu' : bigint,
  'totalPaye' : bigint,
  'totalFaitNonAnnule' : bigint,
  'totalEnAttente' : bigint,
  'totalReelRecu' : bigint,
}
export type Time = bigint;
export interface TotauxListingMensuel {
  'totalTotalReelRecu' : bigint,
  'totalDuesIndividuelles' : bigint,
  'totalSoldeRestantPositif' : bigint,
  'totalFaitEtPaye' : bigint,
  'totalDuMois' : bigint,
  'totalRendezVousFaits' : bigint,
  'totalSommesDues' : bigint,
  'totalNbRendezVousFaits' : bigint,
  'totalPayeMois' : bigint,
  'totalSoldeRestantNegatif' : bigint,
}
export type TypeRepetition = { 'annuelle' : null } |
  { 'aucune' : null } |
  { 'hebdomadaire' : JoursSemaine } |
  { 'mensuelle' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClientRecord' : ActorMethod<
    [string, string, string, string, string, string, [] | [Uint8Array]],
    bigint
  >,
  'ajouterRendezVous' : ActorMethod<
    [
      Time,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      TypeRepetition,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculatePaidThisYear' : ActorMethod<[string], bigint>,
  'deleteClientRecord' : ActorMethod<[bigint], undefined>,
  'deleteRendezVous' : ActorMethod<[bigint, DemandeEdition], undefined>,
  'getAllClientRecords' : ActorMethod<[], Array<ClientRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientRecord' : ActorMethod<[bigint], [] | [ClientRecord]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getTotalReelRecu' : ActorMethod<[bigint, bigint], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handleMontantPayeUpdateWithCredits' : ActorMethod<[bigint, bigint], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'modifierRendezVous' : ActorMethod<
    [
      bigint,
      Time,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      TypeRepetition,
      DemandeEdition,
    ],
    undefined
  >,
  'obtenirCreditClient' : ActorMethod<[string], bigint>,
  'obtenirListingMensuel' : ActorMethod<
    [bigint, bigint],
    [Array<DomaineListingMensuel>, TotauxListingMensuel]
  >,
  'obtenirRapportPDF' : ActorMethod<[RapportPDFRequest], Array<RapportPDFData>>,
  'obtenirRendezVous' : ActorMethod<[bigint], RendezVous>,
  'obtenirRendezVousParReference' : ActorMethod<[string], Array<RendezVous>>,
  'obtenirRendezVousParStatut' : ActorMethod<[boolean], Array<RendezVous>>,
  'obtenirStatistiquesFinancieres' : ActorMethod<[], StatistiquesFinancieres>,
  'obtenirTousLesRendezVous' : ActorMethod<[], Array<RendezVous>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClientRecord' : ActorMethod<
    [bigint, string, string, string, string, string, string, [] | [Uint8Array]],
    undefined
  >,
  'updateCreditClient' : ActorMethod<[string, bigint], undefined>,
  'updateRendezVousStatus' : ActorMethod<
    [bigint, [] | [boolean], [] | [boolean], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];