/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RapportPDFRequest {
    rapportType: RapportType;
    period: bigint;
    year: bigint;
}
export type Time = bigint;
export interface ClientRecord {
    id: bigint;
    service: string;
    clientName: string;
    owner: Principal;
    referenceClient: string;
    address: string;
    notes: string;
    photo?: Uint8Array;
    phoneNumber: string;
}
export type TypeRepetition = {
    __kind__: "annuelle";
    annuelle: null;
} | {
    __kind__: "aucune";
    aucune: null;
} | {
    __kind__: "hebdomadaire";
    hebdomadaire: JoursSemaine;
} | {
    __kind__: "mensuelle";
    mensuelle: null;
};
export interface DashboardStats {
    revenusPercus: bigint;
    totalRecu2026: bigint;
    revenuMoyen2026: bigint;
    revenusPercusMois: bigint;
    totalDue: bigint;
    totalRevenusMensuels2026: Array<bigint>;
    totalReelRecu: bigint;
}
export interface JoursSemaine {
    mardi: boolean;
    samedi: boolean;
    dimanche: boolean;
    jeudi: boolean;
    lundi: boolean;
    vendredi: boolean;
    mercredi: boolean;
}
export interface TotauxListingMensuel {
    totalTotalReelRecu: bigint;
    totalDuesIndividuelles: bigint;
    totalSoldeRestantPositif: bigint;
    totalFaitEtPaye: bigint;
    totalDuMois: bigint;
    totalRendezVousFaits: bigint;
    totalSommesDues: bigint;
    totalNbRendezVousFaits: bigint;
    totalPayeMois: bigint;
    totalSoldeRestantNegatif: bigint;
}
export interface RendezVous {
    id: bigint;
    montantDu: bigint;
    service: string;
    dateHeure: Time;
    owner: Principal;
    fait: boolean;
    heureFin: string;
    nomClient: string;
    annule: boolean;
    repetition: TypeRepetition;
    paiementAnticipe: boolean;
    montantPaye: bigint;
    referenceClient: string;
    notes: string;
    adresse: string;
    commentaireManuel: string;
    heureDebut: string;
    numeroTelephone: string;
}
export interface StatistiquesFinancieres {
    totalDuesIndividuelles: bigint;
    totalFaitEtPaye: bigint;
    totalDu: bigint;
    totalPaye: bigint;
    totalFaitNonAnnule: bigint;
    totalEnAttente: bigint;
    totalReelRecu: bigint;
}
export interface RapportPDFData {
    nbRendezVousFaits: bigint;
    nomClient: string;
    totalSommesDues: bigint;
    referenceClient: string;
    totalSommesRecues: bigint;
    totalCredits: bigint;
}
export interface DomaineListingMensuel {
    creditMois: bigint;
    totalDuesIndividuelles: bigint;
    totalFaitEtPaye: bigint;
    rendezVousFaitsTotal: bigint;
    totalDuMois: bigint;
    nbRendezVousFaits: bigint;
    nomClient: string;
    soldeCumule: bigint;
    totalSommesDues: bigint;
    finExerciceCredit: bigint;
    creditFinMois: bigint;
    referenceClient: string;
    soldeRestant: bigint;
    totalPayeMois: bigint;
    creditCumule: bigint;
    totalReelRecu: bigint;
}
export interface UserProfile {
    name: string;
}
export enum DemandeEdition {
    unique = "unique",
    futursDuClient = "futursDuClient"
}
export enum RapportType {
    annuel = "annuel",
    hebdomadaire = "hebdomadaire",
    mensuel = "mensuel"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addClientRecord(clientName: string, referenceClient: string, phoneNumber: string, address: string, service: string, notes: string, photo: Uint8Array | null): Promise<bigint>;
    ajouterRendezVous(dateHeure: Time, heureDebut: string, heureFin: string, nomClient: string, referenceClient: string, numeroTelephone: string, adresse: string, service: string, notes: string, montantDu: bigint, repetition: TypeRepetition): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculatePaidThisYear(referenceClient: string): Promise<bigint>;
    deleteClientRecord(id: bigint): Promise<void>;
    deleteRendezVous(id: bigint, demandeEdition: DemandeEdition): Promise<void>;
    getAllClientRecords(): Promise<Array<ClientRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientRecord(id: bigint): Promise<ClientRecord | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getTotalReelRecu(year: bigint, month: bigint): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handleMontantPayeUpdateWithCredits(id: bigint, montantPaye: bigint): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    modifierRendezVous(id: bigint, dateHeure: Time, heureDebut: string, heureFin: string, nomClient: string, referenceClient: string, numeroTelephone: string, adresse: string, service: string, notes: string, montantDu: bigint, repetition: TypeRepetition, demandeEdition: DemandeEdition): Promise<void>;
    obtenirCreditClient(referenceClient: string): Promise<bigint>;
    obtenirListingMensuel(year: bigint, month: bigint): Promise<[Array<DomaineListingMensuel>, TotauxListingMensuel]>;
    obtenirRapportPDF(request: RapportPDFRequest): Promise<Array<RapportPDFData>>;
    obtenirRendezVous(id: bigint): Promise<RendezVous>;
    obtenirRendezVousParReference(referenceClient: string): Promise<Array<RendezVous>>;
    obtenirRendezVousParStatut(paye: boolean): Promise<Array<RendezVous>>;
    obtenirStatistiquesFinancieres(): Promise<StatistiquesFinancieres>;
    obtenirTousLesRendezVous(): Promise<Array<RendezVous>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClientRecord(id: bigint, clientName: string, referenceClient: string, phoneNumber: string, address: string, service: string, notes: string, photo: Uint8Array | null): Promise<void>;
    updateCreditClient(referenceClient: string, nouveauCredit: bigint): Promise<void>;
    updateRendezVousStatus(id: bigint, fait: boolean | null, annule: boolean | null, commentaireManuel: string | null): Promise<void>;
}
import type { ClientRecord as _ClientRecord, DemandeEdition as _DemandeEdition, JoursSemaine as _JoursSemaine, RapportPDFRequest as _RapportPDFRequest, RapportType as _RapportType, RendezVous as _RendezVous, Time as _Time, TypeRepetition as _TypeRepetition, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addClientRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Uint8Array | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addClientRecord(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClientRecord(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async ajouterRendezVous(arg0: Time, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: bigint, arg10: TypeRepetition): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.ajouterRendezVous(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_TypeRepetition_n2(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ajouterRendezVous(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_TypeRepetition_n2(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculatePaidThisYear(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePaidThisYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePaidThisYear(arg0);
            return result;
        }
    }
    async deleteClientRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClientRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClientRecord(arg0);
            return result;
        }
    }
    async deleteRendezVous(arg0: bigint, arg1: DemandeEdition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRendezVous(arg0, to_candid_DemandeEdition_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRendezVous(arg0, to_candid_DemandeEdition_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllClientRecords(): Promise<Array<ClientRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClientRecords();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClientRecords();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientRecord(arg0: bigint): Promise<ClientRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientRecord(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientRecord(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getTotalReelRecu(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalReelRecu(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalReelRecu(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleMontantPayeUpdateWithCredits(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.handleMontantPayeUpdateWithCredits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleMontantPayeUpdateWithCredits(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async modifierRendezVous(arg0: bigint, arg1: Time, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: bigint, arg11: TypeRepetition, arg12: DemandeEdition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.modifierRendezVous(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_TypeRepetition_n2(this._uploadFile, this._downloadFile, arg11), to_candid_DemandeEdition_n6(this._uploadFile, this._downloadFile, arg12));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifierRendezVous(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_TypeRepetition_n2(this._uploadFile, this._downloadFile, arg11), to_candid_DemandeEdition_n6(this._uploadFile, this._downloadFile, arg12));
            return result;
        }
    }
    async obtenirCreditClient(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirCreditClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirCreditClient(arg0);
            return result;
        }
    }
    async obtenirListingMensuel(arg0: bigint, arg1: bigint): Promise<[Array<DomaineListingMensuel>, TotauxListingMensuel]> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirListingMensuel(arg0, arg1);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirListingMensuel(arg0, arg1);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async obtenirRapportPDF(arg0: RapportPDFRequest): Promise<Array<RapportPDFData>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirRapportPDF(to_candid_RapportPDFRequest_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirRapportPDF(to_candid_RapportPDFRequest_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async obtenirRendezVous(arg0: bigint): Promise<RendezVous> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirRendezVous(arg0);
                return from_candid_RendezVous_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirRendezVous(arg0);
            return from_candid_RendezVous_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirRendezVousParReference(arg0: string): Promise<Array<RendezVous>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirRendezVousParReference(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirRendezVousParReference(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirRendezVousParStatut(arg0: boolean): Promise<Array<RendezVous>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirRendezVousParStatut(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirRendezVousParStatut(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirStatistiquesFinancieres(): Promise<StatistiquesFinancieres> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirStatistiquesFinancieres();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirStatistiquesFinancieres();
            return result;
        }
    }
    async obtenirTousLesRendezVous(): Promise<Array<RendezVous>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirTousLesRendezVous();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirTousLesRendezVous();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateClientRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: Uint8Array | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateCreditClient(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCreditClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCreditClient(arg0, arg1);
            return result;
        }
    }
    async updateRendezVousStatus(arg0: bigint, arg1: boolean | null, arg2: boolean | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRendezVousStatus(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRendezVousStatus(arg0, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_ClientRecord_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientRecord): ClientRecord {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_RendezVous_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RendezVous): RendezVous {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TypeRepetition_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TypeRepetition): TypeRepetition {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientRecord]): ClientRecord | null {
    return value.length === 0 ? null : from_candid_ClientRecord_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    service: string;
    clientName: string;
    owner: Principal;
    referenceClient: string;
    address: string;
    notes: string;
    photo: [] | [Uint8Array];
    phoneNumber: string;
}): {
    id: bigint;
    service: string;
    clientName: string;
    owner: Principal;
    referenceClient: string;
    address: string;
    notes: string;
    photo?: Uint8Array;
    phoneNumber: string;
} {
    return {
        id: value.id,
        service: value.service,
        clientName: value.clientName,
        owner: value.owner,
        referenceClient: value.referenceClient,
        address: value.address,
        notes: value.notes,
        photo: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.photo)),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    montantDu: bigint;
    service: string;
    dateHeure: _Time;
    owner: Principal;
    fait: boolean;
    heureFin: string;
    nomClient: string;
    annule: boolean;
    repetition: _TypeRepetition;
    paiementAnticipe: boolean;
    montantPaye: bigint;
    referenceClient: string;
    notes: string;
    adresse: string;
    commentaireManuel: string;
    heureDebut: string;
    numeroTelephone: string;
}): {
    id: bigint;
    montantDu: bigint;
    service: string;
    dateHeure: Time;
    owner: Principal;
    fait: boolean;
    heureFin: string;
    nomClient: string;
    annule: boolean;
    repetition: TypeRepetition;
    paiementAnticipe: boolean;
    montantPaye: bigint;
    referenceClient: string;
    notes: string;
    adresse: string;
    commentaireManuel: string;
    heureDebut: string;
    numeroTelephone: string;
} {
    return {
        id: value.id,
        montantDu: value.montantDu,
        service: value.service,
        dateHeure: value.dateHeure,
        owner: value.owner,
        fait: value.fait,
        heureFin: value.heureFin,
        nomClient: value.nomClient,
        annule: value.annule,
        repetition: from_candid_TypeRepetition_n22(_uploadFile, _downloadFile, value.repetition),
        paiementAnticipe: value.paiementAnticipe,
        montantPaye: value.montantPaye,
        referenceClient: value.referenceClient,
        notes: value.notes,
        adresse: value.adresse,
        commentaireManuel: value.commentaireManuel,
        heureDebut: value.heureDebut,
        numeroTelephone: value.numeroTelephone
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annuelle: null;
} | {
    aucune: null;
} | {
    hebdomadaire: _JoursSemaine;
} | {
    mensuelle: null;
}): {
    __kind__: "annuelle";
    annuelle: null;
} | {
    __kind__: "aucune";
    aucune: null;
} | {
    __kind__: "hebdomadaire";
    hebdomadaire: JoursSemaine;
} | {
    __kind__: "mensuelle";
    mensuelle: null;
} {
    return "annuelle" in value ? {
        __kind__: "annuelle",
        annuelle: value.annuelle
    } : "aucune" in value ? {
        __kind__: "aucune",
        aucune: value.aucune
    } : "hebdomadaire" in value ? {
        __kind__: "hebdomadaire",
        hebdomadaire: value.hebdomadaire
    } : "mensuelle" in value ? {
        __kind__: "mensuelle",
        mensuelle: value.mensuelle
    } : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RendezVous>): Array<RendezVous> {
    return value.map((x)=>from_candid_RendezVous_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientRecord>): Array<ClientRecord> {
    return value.map((x)=>from_candid_ClientRecord_n9(_uploadFile, _downloadFile, x));
}
function to_candid_DemandeEdition_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DemandeEdition): _DemandeEdition {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_RapportPDFRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RapportPDFRequest): _RapportPDFRequest {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_RapportType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RapportType): _RapportType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_TypeRepetition_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TypeRepetition): _TypeRepetition {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Uint8Array | null): [] | [Uint8Array] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rapportType: RapportType;
    period: bigint;
    year: bigint;
}): {
    rapportType: _RapportType;
    period: bigint;
    year: bigint;
} {
    return {
        rapportType: to_candid_RapportType_n18(_uploadFile, _downloadFile, value.rapportType),
        period: value.period,
        year: value.year
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RapportType): {
    annuel: null;
} | {
    hebdomadaire: null;
} | {
    mensuel: null;
} {
    return value == RapportType.annuel ? {
        annuel: null
    } : value == RapportType.hebdomadaire ? {
        hebdomadaire: null
    } : value == RapportType.mensuel ? {
        mensuel: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "annuelle";
    annuelle: null;
} | {
    __kind__: "aucune";
    aucune: null;
} | {
    __kind__: "hebdomadaire";
    hebdomadaire: JoursSemaine;
} | {
    __kind__: "mensuelle";
    mensuelle: null;
}): {
    annuelle: null;
} | {
    aucune: null;
} | {
    hebdomadaire: _JoursSemaine;
} | {
    mensuelle: null;
} {
    return value.__kind__ === "annuelle" ? {
        annuelle: value.annuelle
    } : value.__kind__ === "aucune" ? {
        aucune: value.aucune
    } : value.__kind__ === "hebdomadaire" ? {
        hebdomadaire: value.hebdomadaire
    } : value.__kind__ === "mensuelle" ? {
        mensuelle: value.mensuelle
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DemandeEdition): {
    unique: null;
} | {
    futursDuClient: null;
} {
    return value == DemandeEdition.unique ? {
        unique: null
    } : value == DemandeEdition.futursDuClient ? {
        futursDuClient: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
